# Update apt database on first boot (run 'apt-get update').
# Note, if packages are given, or package_upgrade is true, then
# update will be done independent of this setting.
package_update: false
# Upgrade the instance on first boot
# (ie run apt-get upgrade)
package_upgrade: true

disk_setup:
  /dev/sdc:
    table_type: 'mbr'
    layout: true
    overwrite: false

fs_setup:
  - filesystem: 'ext4'
    device: '/dev/sdc'
    overwrite: false

mounts:
 - [ sdc, /data, "auto", "defaults,nofail", "1", "2" ]

# Install additional packages on first boot
packages:
 - git-core

runcmd:
  - 'sudo apt-get -y install apt-transport-https ca-certificates curl software-properties-common'
  - 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'
  - 'sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
  - 'sudo apt-get -y update'
  - 'sudo apt-get -y install docker-ce'
  - 'sudo usermod -aG docker root'
  - 'sudo docker pull jenkinsci/blueocean'
  - 'sudo mkdir -p /data/jenkins'
  - 'sudo git clone ${git_repo_url} /data/jenkins/home'
  - 'sudo chown -R root /data/jenkins'
  - 'sudo docker run -u root --restart always -d -p 8080:8080 -p 50000:50000 -v /data/jenkins/home:/var/jenkins_home  -v /var/run/docker.sock:/var/run/docker.sock jenkinsci/blueocean'


# final_message
# default: cloud-init boot finished at $TIMESTAMP. Up $UPTIME seconds
# this message is written by cloud-final when the system is finished
# its first boot
final_message: "Jenkins server is finally up, after $UPTIME seconds"